baseURL: ''
languageCode: en-us
title: Hugo-profile
googleanalytics: UA-xxxxxx-x
disqusShortname: null
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  tag: tags
  category: categories
enableEmoji: true
params:
  favicon: /images/fav.png
  description: A high performance hugo theme for personal portfolio and blog.
  copyright: '2021'
  customMenus:
    - name: Blog
      Url: /blog
    - name: About
      Url: /#
  socialicontop: false
  socialiconfooter: true
  name: Gurusabarish
  github: 'https://github.com/gurusabarish'
  linkedin: 'https://linkedin.com/in/gurusabarish'
  twitter: 'https://twitter.com/gurusabarishh'
  instagram: 'https://instagram.com/gurusabarishh'
  facebook: 'https://facebook.com'
  profile_image: /images/gurusabarish.webp
  descripe_l1_person: >-
    Hi, I'm Gurusabarish, a passionate web developer and ML engineer. I tend to
    make use of modern web technologies to build websites that looks great,
    feels fantastic, and functions correctly.
  descripe_l2_person: ''
  useresume: true
  customname: ''
  resumelink: ''
  usedothings: true
  Things:
    - logo: fab fa-python
      title: Python
      description: I build something beautiful using Python.
    - logo: fas fa-robot
      title: Machine learning
      description: I train robust models for various tasks.
    - logo: fab fa-html5
      title: Things for web
      description: I love to build things for web
  showdescription: false
  tweet: true
  recentposts: true
theme: hugo profile
themesDir: themes
publishDir: public
